== Table of contents javascript
This is a simple way to create table of contents using header tags.
It will retrieve the header tags inside the contents ID and spit out into the toc ID.

link:https://htmlpreview.github.io/?https://github.com/PepperAddict/easy_toc_js/blob/master/index.html[demo]

== Usage
=== the Content
Wrap the content that you want with a div ID: *contents*. 
Example below will not include header title since it is not inside the contents div.

.example
----
<h1>title</h1>

<div id="contents">
<h1>listing 1</h1>
<h1>Listing 2</h1>
</div>
----

=== the TOC
We need a placeholder for the actual table of contents. To do this insert a div with the ID: *toc*.
Inside the div, be sure to have the title of the table of contents if you need any.

.example
----
<div id="toc">
Table of contents
</div>
----

=== the JS
the javascript will only use h1 tags as the parent and h2, h3, h4, and so on are the children.
You can easily modify the condition to your liking.

== That's it.
You can now easily customize the style your way or use mine.