== Table of contents javascript
This is a simple way to create table of contents using header tags.
It will retrieve the header tags inside the contents ID and spit out into the toc ID.

== Usage
=== the Content
Wrap the content that you want with the ID: *contents*. 
Example below will not include header title since it is not inside the contents div.

----
<h1>title</h1>

<div id="contents">
<h1>listing 1</h1>
<h1>Listing 2</h1>
</div>
----

=== the TOC
We need a placeholder for the actual table of contents. To do this, insert a div with the ID: *toc*.
Inside the div, be sure to have the title of the table of contents if you want any.


----
<div id="toc">
Table of contents
</div>
----

=== the JS
The javascript will only use h1 tags as the parent and h2, h3, h4, and so on are the children.
You can easily modify the condition to your liking.

----
window.onload = function () {
    var toc = '';
    var level = 0;
    var search = /<h([\d])>([^<]+)<\/h([\d])>/gi;

    function sit (regExp, substr, subReplacer, replacement) {
        level = parseInt(substr);
        var anchor = subReplacer.replace(/ /g, "_");
        if (substr < 2){
        toc += "<dt><a href=\"#" + anchor + "\">" + subReplacer + "</a></dt>";   
        }
        else if (substr >= 2) {
        toc += "<dd><a href=\"#" + anchor + "\">" + subReplacer + "</a></dd>";              
        }        
        return "<h" + substr + "><a name=\"" + anchor + "\">" + subReplacer + "</a></h" + replacement + ">";  
}

    document.getElementById("contents").innerHTML = document.getElementById("contents").innerHTML.replace(search, sit);
    document.getElementById("toc").innerHTML += toc;
};
----

== Note
Keep in mind when styling, I decided to use dt and dd instead of the usual ul and li. I just found dt and dd easier to separate in one line.

link:https://www.w3schools.com/tags/tag_dd.asp[w3school:dd tag]

== That's it.
You can now easily customize the style your way or use mine.